# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_taskManager/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LRCSNet(object):
    def setupUi(self, LRCSNet):
        LRCSNet.setObjectName("LRCSNet")
        LRCSNet.resize(1178, 783)
        self.centralwidget = QtWidgets.QWidget(LRCSNet)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(0, 36))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_button.setIcon(icon)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.loop_button = QtWidgets.QPushButton(self.centralwidget)
        self.loop_button.setMinimumSize(QtCore.QSize(0, 36))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/exchange_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("img/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.loop_button.setIcon(icon1)
        self.loop_button.setCheckable(True)
        self.loop_button.setObjectName("loop_button")
        self.horizontalLayout_2.addWidget(self.loop_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 36))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon2)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setMinimumSize(QtCore.QSize(0, 36))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon3)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.add_button)
        self.clean_button = QtWidgets.QPushButton(self.centralwidget)
        self.clean_button.setMinimumSize(QtCore.QSize(0, 36))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clean_button.setIcon(icon4)
        self.clean_button.setObjectName("clean_button")
        self.horizontalLayout_2.addWidget(self.clean_button)
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setMinimumSize(QtCore.QSize(0, 36))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward_button.setIcon(icon5)
        self.forward_button.setObjectName("forward_button")
        self.horizontalLayout_2.addWidget(self.forward_button)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 36))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/resume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setMinimumSize(QtCore.QSize(0, 36))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/rubik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predict_button.setIcon(icon7)
        self.predict_button.setIconSize(QtCore.QSize(20, 20))
        self.predict_button.setObjectName("predict_button")
        self.horizontalLayout_2.addWidget(self.predict_button)
        self.dashboard_button = QtWidgets.QPushButton(self.centralwidget)
        self.dashboard_button.setMinimumSize(QtCore.QSize(0, 36))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/speedometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_button.setIcon(icon8)
        self.dashboard_button.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button.setObjectName("dashboard_button")
        self.horizontalLayout_2.addWidget(self.dashboard_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(801, 601))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setRowCount(21)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(181, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.AvailableGPUs = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AvailableGPUs.sizePolicy().hasHeightForWidth())
        self.AvailableGPUs.setSizePolicy(sizePolicy)
        self.AvailableGPUs.setMaximumSize(QtCore.QSize(181, 16777215))
        self.AvailableGPUs.setObjectName("AvailableGPUs")
        self.verticalLayout.addWidget(self.AvailableGPUs)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(181, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ongoing_process = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ongoing_process.sizePolicy().hasHeightForWidth())
        self.ongoing_process.setSizePolicy(sizePolicy)
        self.ongoing_process.setMaximumSize(QtCore.QSize(181, 16777215))
        self.ongoing_process.setObjectName("ongoing_process")
        self.verticalLayout.addWidget(self.ongoing_process)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        LRCSNet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LRCSNet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setEnabled(True)
        self.menuMenu.setObjectName("menuMenu")
        self.menuPlugin = QtWidgets.QMenu(self.menubar)
        self.menuPlugin.setObjectName("menuPlugin")
        LRCSNet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LRCSNet)
        self.statusbar.setObjectName("statusbar")
        LRCSNet.setStatusBar(self.statusbar)
        self.About_us = QtWidgets.QAction(LRCSNet)
        self.About_us.setObjectName("About_us")
        self.Activations = QtWidgets.QAction(LRCSNet)
        self.Activations.setObjectName("Activations")
        self.Exit = QtWidgets.QAction(LRCSNet)
        self.Exit.setObjectName("Exit")
        self.Loss_Landscape = QtWidgets.QAction(LRCSNet)
        self.Loss_Landscape.setObjectName("Loss_Landscape")
        self.Random_Forest = QtWidgets.QAction(LRCSNet)
        self.Random_Forest.setObjectName("Random_Forest")
        self.Volumes_Viewer = QtWidgets.QAction(LRCSNet)
        self.Volumes_Viewer.setObjectName("Volumes_Viewer")
        self.Metrics = QtWidgets.QAction(LRCSNet)
        self.Metrics.setObjectName("Metrics")
        self.AugViewer = QtWidgets.QAction(LRCSNet)
        self.AugViewer.setObjectName("AugViewer")
        self.menuMenu.addAction(self.About_us)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.Exit)
        self.menuPlugin.addAction(self.Activations)
        self.menuPlugin.addAction(self.Loss_Landscape)
        self.menuPlugin.addAction(self.Random_Forest)
        self.menuPlugin.addAction(self.Volumes_Viewer)
        self.menuPlugin.addAction(self.Metrics)
        self.menuPlugin.addAction(self.AugViewer)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuPlugin.menuAction())

        self.retranslateUi(LRCSNet)
        QtCore.QMetaObject.connectSlotsByName(LRCSNet)

    def retranslateUi(self, LRCSNet):
        _translate = QtCore.QCoreApplication.translate
        LRCSNet.setWindowTitle(_translate("LRCSNet", "MainWindow"))
        self.start_button.setText(_translate("LRCSNet", "Start(A)"))
        self.start_button.setShortcut(_translate("LRCSNet", "A"))
        self.loop_button.setText(_translate("LRCSNet", "Loop(S)"))
        self.loop_button.setShortcut(_translate("LRCSNet", "S"))
        self.stop_button.setText(_translate("LRCSNet", "Stop(D)"))
        self.stop_button.setShortcut(_translate("LRCSNet", "D"))
        self.add_button.setText(_translate("LRCSNet", "Add(Q)"))
        self.add_button.setShortcut(_translate("LRCSNet", "Q"))
        self.clean_button.setText(_translate("LRCSNet", "Clean(W)"))
        self.clean_button.setShortcut(_translate("LRCSNet", "W"))
        self.forward_button.setText(_translate("LRCSNet", "Forward(E)"))
        self.forward_button.setShortcut(_translate("LRCSNet", "E"))
        self.pushButton.setText(_translate("LRCSNet", "Resume(Z)"))
        self.pushButton.setShortcut(_translate("LRCSNet", "Z"))
        self.predict_button.setText(_translate("LRCSNet", "Predict(X)"))
        self.predict_button.setShortcut(_translate("LRCSNet", "X"))
        self.dashboard_button.setText(_translate("LRCSNet", "Dashboard(C)"))
        self.dashboard_button.setShortcut(_translate("LRCSNet", "C"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("LRCSNet", "model"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("LRCSNet", "conv nb"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("LRCSNet", "kernel size"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("LRCSNet", "batch size"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("LRCSNet", "window size"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("LRCSNet", "nb_epoch"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("LRCSNet", "lr type"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("LRCSNet", "init lr"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("LRCSNet", "k param"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("LRCSNet", "p param"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("LRCSNet", "loss fn"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("LRCSNet", "act fn"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("LRCSNet", "batch norm"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("LRCSNet", "augmentation"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("LRCSNet", "dropout"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("LRCSNet", "sv step"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("LRCSNet", "tb step"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("LRCSNet", "mode"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("LRCSNet", "comment"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("LRCSNet", "trn repo path"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("LRCSNet", "val repo path"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("LRCSNet", "Available GPUs:"))
        self.label_2.setText(_translate("LRCSNet", "Ongoing Process:"))
        self.menuMenu.setTitle(_translate("LRCSNet", "Menu"))
        self.menuPlugin.setTitle(_translate("LRCSNet", "plug-ins"))
        self.About_us.setText(_translate("LRCSNet", "About us"))
        self.Activations.setText(_translate("LRCSNet", "Activations"))
        self.Exit.setText(_translate("LRCSNet", "Exit"))
        self.Loss_Landscape.setText(_translate("LRCSNet", "Loss-Landscape"))
        self.Random_Forest.setText(_translate("LRCSNet", "Random-Forest"))
        self.Volumes_Viewer.setText(_translate("LRCSNet", "Volumes-Viewer"))
        self.Metrics.setText(_translate("LRCSNet", "Metrics"))
        self.AugViewer.setText(_translate("LRCSNet", "AugViewer"))

