# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LRCSNet(object):
    def setupUi(self, LRCSNet):
        LRCSNet.setObjectName("LRCSNet")
        LRCSNet.resize(942, 701)
        self.centralwidget = QtWidgets.QWidget(LRCSNet)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 91, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_taskManager/001-play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 10, 91, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_taskManager/002-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 10, 91, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_taskManager/001-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 10, 101, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_taskManager/002-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.AvailableGPUs = QtWidgets.QListWidget(self.centralwidget)
        self.AvailableGPUs.setGeometry(QtCore.QRect(800, 70, 111, 571))
        self.AvailableGPUs.setObjectName("AvailableGPUs")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 771, 571))
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setRowCount(18)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 30, 101, 16))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 10, 91, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("_taskManager/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        LRCSNet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LRCSNet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        LRCSNet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LRCSNet)
        self.statusbar.setObjectName("statusbar")
        LRCSNet.setStatusBar(self.statusbar)
        self.actionAbout_us = QtWidgets.QAction(LRCSNet)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuMenu.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(LRCSNet)
        QtCore.QMetaObject.connectSlotsByName(LRCSNet)

    def retranslateUi(self, LRCSNet):
        _translate = QtCore.QCoreApplication.translate
        LRCSNet.setWindowTitle(_translate("LRCSNet", "MainWindow"))
        self.pushButton.setText(_translate("LRCSNet", "Start (a)"))
        self.pushButton_2.setText(_translate("LRCSNet", "Stop(d)"))
        self.pushButton_3.setText(_translate("LRCSNet", "Add(q)"))
        self.pushButton_4.setText(_translate("LRCSNet", "Clear(w)"))
        self.pushButton_5.setText(_translate("LRCSNet", "Loop (s)"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("LRCSNet", "model"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("LRCSNet", "conv nb"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("LRCSNet", "kernel size"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("LRCSNet", "batch size"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("LRCSNet", "window size"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("LRCSNet", "nb_epoch"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("LRCSNet", "lr type"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("LRCSNet", "init lr"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("LRCSNet", "k param"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("LRCSNet", "p param"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("LRCSNet", "loss fn"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("LRCSNet", "act fn"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("LRCSNet", "batch norm"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("LRCSNet", "augmentation"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("LRCSNet", "dropout"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("LRCSNet", "sv step"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("LRCSNet", "tb step"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("LRCSNet", "mode"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("LRCSNet", "Available GPUs:"))
        self.menuMenu.setTitle(_translate("LRCSNet", "Menu"))
        self.menuQuit.setTitle(_translate("LRCSNet", "Quit"))
        self.actionAbout_us.setText(_translate("LRCSNet", "About us"))

