# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LRCSNet(object):
    def setupUi(self, LRCSNet):
        LRCSNet.setObjectName("LRCSNet")
        LRCSNet.resize(1019, 701)
        self.centralwidget = QtWidgets.QWidget(LRCSNet)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(20, 10, 91, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_taskManager/001-play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_button.setIcon(icon)
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(200, 10, 91, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_taskManager/002-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon1)
        self.stop_button.setObjectName("stop_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(290, 10, 91, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("_taskManager/001-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon2)
        self.add_button.setObjectName("add_button")
        self.clean_button = QtWidgets.QPushButton(self.centralwidget)
        self.clean_button.setGeometry(QtCore.QRect(380, 10, 101, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("_taskManager/002-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clean_button.setIcon(icon3)
        self.clean_button.setObjectName("clean_button")
        self.AvailableGPUs = QtWidgets.QListWidget(self.centralwidget)
        self.AvailableGPUs.setGeometry(QtCore.QRect(890, 110, 111, 231))
        self.AvailableGPUs.setObjectName("AvailableGPUs")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 861, 571))
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setRowCount(18)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(890, 90, 101, 16))
        self.label.setObjectName("label")
        self.loop_button = QtWidgets.QPushButton(self.centralwidget)
        self.loop_button.setGeometry(QtCore.QRect(110, 10, 91, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("_taskManager/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loop_button.setIcon(icon4)
        self.loop_button.setObjectName("loop_button")
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setGeometry(QtCore.QRect(480, 10, 111, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("_taskManager/001-reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward_button.setIcon(icon5)
        self.forward_button.setObjectName("forward_button")
        self.dashboard_button = QtWidgets.QPushButton(self.centralwidget)
        self.dashboard_button.setGeometry(QtCore.QRect(740, 10, 131, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("_taskManager/002-speedometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_button.setIcon(icon6)
        self.dashboard_button.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button.setObjectName("dashboard_button")
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setGeometry(QtCore.QRect(630, 10, 112, 41))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("_taskManager/rubik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predict_button.setIcon(icon7)
        self.predict_button.setIconSize(QtCore.QSize(20, 20))
        self.predict_button.setObjectName("predict_button")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(600, 10, 20, 51))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ongoing_process = QtWidgets.QListWidget(self.centralwidget)
        self.ongoing_process.setGeometry(QtCore.QRect(890, 390, 111, 231))
        self.ongoing_process.setObjectName("ongoing_process")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 370, 111, 16))
        self.label_2.setObjectName("label_2")
        LRCSNet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LRCSNet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        LRCSNet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LRCSNet)
        self.statusbar.setObjectName("statusbar")
        LRCSNet.setStatusBar(self.statusbar)
        self.actionAbout_us = QtWidgets.QAction(LRCSNet)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuMenu.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(LRCSNet)
        QtCore.QMetaObject.connectSlotsByName(LRCSNet)

    def retranslateUi(self, LRCSNet):
        _translate = QtCore.QCoreApplication.translate
        LRCSNet.setWindowTitle(_translate("LRCSNet", "MainWindow"))
        self.start_button.setText(_translate("LRCSNet", "Start(a)"))
        self.start_button.setShortcut(_translate("LRCSNet", "A"))
        self.stop_button.setText(_translate("LRCSNet", "Stop(d)"))
        self.stop_button.setShortcut(_translate("LRCSNet", "D"))
        self.add_button.setText(_translate("LRCSNet", "Add(q)"))
        self.add_button.setShortcut(_translate("LRCSNet", "Q"))
        self.clean_button.setText(_translate("LRCSNet", "Clean(w)"))
        self.clean_button.setShortcut(_translate("LRCSNet", "W"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("LRCSNet", "model"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("LRCSNet", "conv nb"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("LRCSNet", "kernel size"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("LRCSNet", "batch size"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("LRCSNet", "window size"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("LRCSNet", "nb_epoch"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("LRCSNet", "lr type"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("LRCSNet", "init lr"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("LRCSNet", "k param"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("LRCSNet", "p param"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("LRCSNet", "loss fn"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("LRCSNet", "act fn"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("LRCSNet", "batch norm"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("LRCSNet", "augmentation"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("LRCSNet", "dropout"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("LRCSNet", "sv step"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("LRCSNet", "tb step"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("LRCSNet", "mode"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("LRCSNet", "Available GPUs:"))
        self.loop_button.setText(_translate("LRCSNet", "Loop(s)"))
        self.loop_button.setShortcut(_translate("LRCSNet", "S"))
        self.forward_button.setText(_translate("LRCSNet", "Forward(e)"))
        self.forward_button.setShortcut(_translate("LRCSNet", "E"))
        self.dashboard_button.setText(_translate("LRCSNet", "Dashboard(r)"))
        self.dashboard_button.setShortcut(_translate("LRCSNet", "R"))
        self.predict_button.setText(_translate("LRCSNet", "Predict(p)"))
        self.label_2.setText(_translate("LRCSNet", "Ongoing Process:"))
        self.menuMenu.setTitle(_translate("LRCSNet", "Menu"))
        self.menuQuit.setTitle(_translate("LRCSNet", "Quit"))
        self.actionAbout_us.setText(_translate("LRCSNet", "About us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LRCSNet = QtWidgets.QMainWindow()
    ui = Ui_LRCSNet()
    ui.setupUi(LRCSNet)
    LRCSNet.show()
    sys.exit(app.exec_())

