# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_taskManager/metric_design.ui',
# licensing of '_taskManager/metric_design.ui' applies.
#
# Created: Tue Feb 16 18:44:42 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_metricViewer(object):
    def setupUi(self, metricViewer):
        metricViewer.setObjectName("metricViewer")
        metricViewer.resize(1199, 965)
        self.gridLayout = QtWidgets.QGridLayout(metricViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.total_pix = QtWidgets.QLabel(metricViewer)
        self.total_pix.setAlignment(QtCore.Qt.AlignCenter)
        self.total_pix.setObjectName("total_pix")
        self.verticalLayout_4.addWidget(self.total_pix)
        self.total_IoU = QtWidgets.QLabel(metricViewer)
        self.total_IoU.setAlignment(QtCore.Qt.AlignCenter)
        self.total_IoU.setObjectName("total_IoU")
        self.verticalLayout_4.addWidget(self.total_IoU)
        self.total_acc = QtWidgets.QLabel(metricViewer)
        self.total_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.total_acc.setObjectName("total_acc")
        self.verticalLayout_4.addWidget(self.total_acc)
        self.line = QtWidgets.QFrame(metricViewer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gt1_vol_frac = QtWidgets.QListWidget(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gt1_vol_frac.sizePolicy().hasHeightForWidth())
        self.gt1_vol_frac.setSizePolicy(sizePolicy)
        self.gt1_vol_frac.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gt1_vol_frac.setObjectName("gt1_vol_frac")
        self.verticalLayout_2.addWidget(self.gt1_vol_frac)
        self.label_5 = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gt1_surf = QtWidgets.QListWidget(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gt1_surf.sizePolicy().hasHeightForWidth())
        self.gt1_surf.setSizePolicy(sizePolicy)
        self.gt1_surf.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gt1_surf.setObjectName("gt1_surf")
        self.verticalLayout_2.addWidget(self.gt1_surf)
        self.label_2 = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gt1_interf = QtWidgets.QListWidget(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gt1_interf.sizePolicy().hasHeightForWidth())
        self.gt1_interf.setSizePolicy(sizePolicy)
        self.gt1_interf.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gt1_interf.setObjectName("gt1_interf")
        self.verticalLayout_2.addWidget(self.gt1_interf)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.raw_frame = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.raw_frame.sizePolicy().hasHeightForWidth())
        self.raw_frame.setSizePolicy(sizePolicy)
        self.raw_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.raw_frame.setMouseTracking(False)
        self.raw_frame.setAcceptDrops(True)
        self.raw_frame.setAutoFillBackground(False)
        self.raw_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.raw_frame.setLineWidth(1)
        self.raw_frame.setMidLineWidth(0)
        self.raw_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_frame.setObjectName("raw_frame")
        self.horizontalLayout_2.addWidget(self.raw_frame)
        self.diff_frame = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.diff_frame.sizePolicy().hasHeightForWidth())
        self.diff_frame.setSizePolicy(sizePolicy)
        self.diff_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.diff_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.diff_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.diff_frame.setObjectName("diff_frame")
        self.horizontalLayout_2.addWidget(self.diff_frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gt1_frame = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gt1_frame.sizePolicy().hasHeightForWidth())
        self.gt1_frame.setSizePolicy(sizePolicy)
        self.gt1_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.gt1_frame.setAcceptDrops(True)
        self.gt1_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.gt1_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.gt1_frame.setObjectName("gt1_frame")
        self.horizontalLayout_3.addWidget(self.gt1_frame)
        self.gt2_frame = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gt2_frame.sizePolicy().hasHeightForWidth())
        self.gt2_frame.setSizePolicy(sizePolicy)
        self.gt2_frame.setMinimumSize(QtCore.QSize(400, 400))
        self.gt2_frame.setAcceptDrops(True)
        self.gt2_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.gt2_frame.setMidLineWidth(0)
        self.gt2_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.gt2_frame.setObjectName("gt2_frame")
        self.horizontalLayout_3.addWidget(self.gt2_frame)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gt2_vol_frac = QtWidgets.QListWidget(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gt2_vol_frac.sizePolicy().hasHeightForWidth())
        self.gt2_vol_frac.setSizePolicy(sizePolicy)
        self.gt2_vol_frac.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gt2_vol_frac.setObjectName("gt2_vol_frac")
        self.verticalLayout_3.addWidget(self.gt2_vol_frac)
        self.label_6 = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.gt2_surf = QtWidgets.QListWidget(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gt2_surf.sizePolicy().hasHeightForWidth())
        self.gt2_surf.setSizePolicy(sizePolicy)
        self.gt2_surf.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gt2_surf.setObjectName("gt2_surf")
        self.verticalLayout_3.addWidget(self.gt2_surf)
        self.label_4 = QtWidgets.QLabel(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.gt2_interf = QtWidgets.QListWidget(metricViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gt2_interf.sizePolicy().hasHeightForWidth())
        self.gt2_interf.setSizePolicy(sizePolicy)
        self.gt2_interf.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gt2_interf.setObjectName("gt2_interf")
        self.verticalLayout_3.addWidget(self.gt2_interf)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clean_button = QtWidgets.QPushButton(metricViewer)
        self.clean_button.setObjectName("clean_button")
        self.horizontalLayout.addWidget(self.clean_button)
        self.add_button = QtWidgets.QPushButton(metricViewer)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.previous_button = QtWidgets.QPushButton(metricViewer)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout.addWidget(self.previous_button)
        self.next_button = QtWidgets.QPushButton(metricViewer)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.save_Button = QtWidgets.QPushButton(metricViewer)
        self.save_Button.setObjectName("save_Button")
        self.horizontalLayout.addWidget(self.save_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.pageSlider = QtWidgets.QScrollBar(metricViewer)
        self.pageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pageSlider.setObjectName("pageSlider")
        self.verticalLayout_4.addWidget(self.pageSlider)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(metricViewer)
        QtCore.QMetaObject.connectSlotsByName(metricViewer)

    def retranslateUi(self, metricViewer):
        metricViewer.setWindowTitle(QtWidgets.QApplication.translate("metricViewer", "Dialog", None, -1))
        self.total_pix.setText(QtWidgets.QApplication.translate("metricViewer", "Total pixels:", None, -1))
        self.total_IoU.setText(QtWidgets.QApplication.translate("metricViewer", "Accuracy:", None, -1))
        self.total_acc.setText(QtWidgets.QApplication.translate("metricViewer", "IoU:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("metricViewer", "Ref. Vol. Frac. (pixel / %):", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("metricViewer", "Ref. Surface (pixel / %):", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("metricViewer", "Ref. Interface (pixel / %):", None, -1))
        self.raw_frame.setText(QtWidgets.QApplication.translate("metricViewer", "Drop a raw tomogram here", None, -1))
        self.diff_frame.setText(QtWidgets.QApplication.translate("metricViewer", "Difference will be shown here", None, -1))
        self.gt1_frame.setText(QtWidgets.QApplication.translate("metricViewer", "Drop a (reference) segmentation here", None, -1))
        self.gt2_frame.setText(QtWidgets.QApplication.translate("metricViewer", "Drop a segmentation here", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("metricViewer", "Vol. Frac. (pixel / %):", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("metricViewer", "Surface (pixel / %):", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("metricViewer", "Interface (pixel / %):", None, -1))
        self.clean_button.setText(QtWidgets.QApplication.translate("metricViewer", "Clean(C)", None, -1))
        self.clean_button.setShortcut(QtWidgets.QApplication.translate("metricViewer", "C", None, -1))
        self.add_button.setText(QtWidgets.QApplication.translate("metricViewer", "Add(A)", None, -1))
        self.add_button.setShortcut(QtWidgets.QApplication.translate("metricViewer", "A", None, -1))
        self.previous_button.setText(QtWidgets.QApplication.translate("metricViewer", "Previous(1)", None, -1))
        self.previous_button.setShortcut(QtWidgets.QApplication.translate("metricViewer", "1", None, -1))
        self.next_button.setText(QtWidgets.QApplication.translate("metricViewer", "Next(2)", None, -1))
        self.next_button.setShortcut(QtWidgets.QApplication.translate("metricViewer", "2", None, -1))
        self.save_Button.setText(QtWidgets.QApplication.translate("metricViewer", "Save(S)", None, -1))
        self.save_Button.setShortcut(QtWidgets.QApplication.translate("metricViewer", "S", None, -1))

