# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volumes_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_volViewer(object):
    def setupUi(self, volViewer):
        volViewer.setObjectName("volViewer")
        volViewer.resize(1041, 597)
        self.gridLayout = QtWidgets.QGridLayout(volViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vol1 = QtWidgets.QLabel(volViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vol1.sizePolicy().hasHeightForWidth())
        self.vol1.setSizePolicy(sizePolicy)
        self.vol1.setMinimumSize(QtCore.QSize(500, 500))
        self.vol1.setAcceptDrops(True)
        self.vol1.setFrameShape(QtWidgets.QFrame.Box)
        self.vol1.setAlignment(QtCore.Qt.AlignCenter)
        self.vol1.setObjectName("vol1")
        self.horizontalLayout.addWidget(self.vol1)
        self.vol2 = QtWidgets.QLabel(volViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vol2.sizePolicy().hasHeightForWidth())
        self.vol2.setSizePolicy(sizePolicy)
        self.vol2.setMinimumSize(QtCore.QSize(500, 500))
        self.vol2.setAcceptDrops(True)
        self.vol2.setFrameShape(QtWidgets.QFrame.Box)
        self.vol2.setMidLineWidth(0)
        self.vol2.setAlignment(QtCore.Qt.AlignCenter)
        self.vol2.setObjectName("vol2")
        self.horizontalLayout.addWidget(self.vol2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.actual_slide = QtWidgets.QLCDNumber(volViewer)
        self.actual_slide.setMidLineWidth(0)
        self.actual_slide.setSmallDecimalPoint(False)
        self.actual_slide.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.actual_slide.setObjectName("actual_slide")
        self.horizontalLayout_2.addWidget(self.actual_slide)
        self.label = QtWidgets.QLabel(volViewer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.total_slides = QtWidgets.QLCDNumber(volViewer)
        self.total_slides.setFrameShadow(QtWidgets.QFrame.Raised)
        self.total_slides.setLineWidth(1)
        self.total_slides.setMidLineWidth(0)
        self.total_slides.setSmallDecimalPoint(False)
        self.total_slides.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.total_slides.setObjectName("total_slides")
        self.horizontalLayout_2.addWidget(self.total_slides)
        self.label_2 = QtWidgets.QLabel(volViewer)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.zoom_button = QtWidgets.QPushButton(volViewer)
        self.zoom_button.setMinimumSize(QtCore.QSize(0, 36))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_button.setIcon(icon)
        self.zoom_button.setCheckable(True)
        self.zoom_button.setChecked(False)
        self.zoom_button.setObjectName("zoom_button")
        self.horizontalLayout_2.addWidget(self.zoom_button)
        self.dezoom_button = QtWidgets.QPushButton(volViewer)
        self.dezoom_button.setMinimumSize(QtCore.QSize(0, 36))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dezoom_button.setIcon(icon1)
        self.dezoom_button.setObjectName("dezoom_button")
        self.horizontalLayout_2.addWidget(self.dezoom_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Slider = QtWidgets.QScrollBar(volViewer)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.verticalLayout.addWidget(self.Slider)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(volViewer)
        QtCore.QMetaObject.connectSlotsByName(volViewer)

    def retranslateUi(self, volViewer):
        _translate = QtCore.QCoreApplication.translate
        volViewer.setWindowTitle(_translate("volViewer", "Dialog"))
        self.vol1.setText(_translate("volViewer", "Drop a folder of images here"))
        self.vol2.setText(_translate("volViewer", "Drop a folder of images here"))
        self.label.setText(_translate("volViewer", "/"))
        self.label_2.setText(_translate("volViewer", "Slides"))
        self.zoom_button.setText(_translate("volViewer", "Zoom-in(A)"))
        self.zoom_button.setShortcut(_translate("volViewer", "A"))
        self.dezoom_button.setText(_translate("volViewer", "Zoom-out(S)"))
        self.dezoom_button.setShortcut(_translate("volViewer", "S"))
