# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './_taskManager/resumeDialog_design.ui',
# licensing of './_taskManager/resumeDialog_design.ui' applies.
#
# Created: Thu Mar 11 18:15:10 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ckptLabel = QtWidgets.QLabel(Dialog)
        self.ckptLabel.setObjectName("ckptLabel")
        self.horizontalLayout.addWidget(self.ckptLabel)
        self.ckptLine = QtWidgets.QLineEdit(Dialog)
        self.ckptLine.setObjectName("ckptLine")
        self.horizontalLayout.addWidget(self.ckptLine)
        self.ckptButton = QtWidgets.QPushButton(Dialog)
        self.ckptButton.setObjectName("ckptButton")
        self.horizontalLayout.addWidget(self.ckptButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.trnPathLabel = QtWidgets.QLabel(Dialog)
        self.trnPathLabel.setObjectName("trnPathLabel")
        self.horizontalLayout_4.addWidget(self.trnPathLabel)
        self.trnPathLine = QtWidgets.QLineEdit(Dialog)
        self.trnPathLine.setObjectName("trnPathLine")
        self.horizontalLayout_4.addWidget(self.trnPathLine)
        self.trnPathButton = QtWidgets.QPushButton(Dialog)
        self.trnPathButton.setObjectName("trnPathButton")
        self.horizontalLayout_4.addWidget(self.trnPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.valPathLabel = QtWidgets.QLabel(Dialog)
        self.valPathLabel.setObjectName("valPathLabel")
        self.horizontalLayout_5.addWidget(self.valPathLabel)
        self.valPathLine = QtWidgets.QLineEdit(Dialog)
        self.valPathLine.setObjectName("valPathLine")
        self.horizontalLayout_5.addWidget(self.valPathLine)
        self.valPathButton = QtWidgets.QPushButton(Dialog)
        self.valPathButton.setObjectName("valPathButton")
        self.horizontalLayout_5.addWidget(self.valPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tstPathLabel = QtWidgets.QLabel(Dialog)
        self.tstPathLabel.setObjectName("tstPathLabel")
        self.horizontalLayout_6.addWidget(self.tstPathLabel)
        self.tstPathLine = QtWidgets.QLineEdit(Dialog)
        self.tstPathLine.setObjectName("tstPathLine")
        self.horizontalLayout_6.addWidget(self.tstPathLine)
        self.tstPathButton = QtWidgets.QPushButton(Dialog)
        self.tstPathButton.setObjectName("tstPathButton")
        self.horizontalLayout_6.addWidget(self.tstPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.whereToSave_label = QtWidgets.QLabel(Dialog)
        self.whereToSave_label.setObjectName("whereToSave_label")
        self.horizontalLayout_12.addWidget(self.whereToSave_label)
        self.whereToSave = QtWidgets.QLineEdit(Dialog)
        self.whereToSave.setObjectName("whereToSave")
        self.horizontalLayout_12.addWidget(self.whereToSave)
        self.whereToSaveButton = QtWidgets.QPushButton(Dialog)
        self.whereToSaveButton.setObjectName("whereToSaveButton")
        self.horizontalLayout_12.addWidget(self.whereToSaveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.new_init_lr_label = QtWidgets.QLabel(Dialog)
        self.new_init_lr_label.setObjectName("new_init_lr_label")
        self.horizontalLayout_9.addWidget(self.new_init_lr_label)
        self.new_init_lr = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_init_lr.sizePolicy().hasHeightForWidth())
        self.new_init_lr.setSizePolicy(sizePolicy)
        self.new_init_lr.setText("")
        self.new_init_lr.setObjectName("new_init_lr")
        self.horizontalLayout_9.addWidget(self.new_init_lr)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.new_lr_dec_ratio_label = QtWidgets.QLabel(Dialog)
        self.new_lr_dec_ratio_label.setObjectName("new_lr_dec_ratio_label")
        self.horizontalLayout_8.addWidget(self.new_lr_dec_ratio_label)
        self.new_lr_dec_ratio = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_lr_dec_ratio.sizePolicy().hasHeightForWidth())
        self.new_lr_dec_ratio.setSizePolicy(sizePolicy)
        self.new_lr_dec_ratio.setText("")
        self.new_lr_dec_ratio.setObjectName("new_lr_dec_ratio")
        self.horizontalLayout_8.addWidget(self.new_lr_dec_ratio)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.new_lr_dec_period_label = QtWidgets.QLabel(Dialog)
        self.new_lr_dec_period_label.setObjectName("new_lr_dec_period_label")
        self.horizontalLayout_7.addWidget(self.new_lr_dec_period_label)
        self.new_lr_dec_period = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_lr_dec_period.sizePolicy().hasHeightForWidth())
        self.new_lr_dec_period.setSizePolicy(sizePolicy)
        self.new_lr_dec_period.setText("")
        self.new_lr_dec_period.setObjectName("new_lr_dec_period")
        self.horizontalLayout_7.addWidget(self.new_lr_dec_period)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sampling_gap_label = QtWidgets.QLabel(Dialog)
        self.sampling_gap_label.setObjectName("sampling_gap_label")
        self.horizontalLayout_10.addWidget(self.sampling_gap_label)
        self.sampling_gap = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampling_gap.sizePolicy().hasHeightForWidth())
        self.sampling_gap.setSizePolicy(sizePolicy)
        self.sampling_gap.setText("")
        self.sampling_gap.setObjectName("sampling_gap")
        self.horizontalLayout_10.addWidget(self.sampling_gap)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stop_cond_label = QtWidgets.QLabel(Dialog)
        self.stop_cond_label.setObjectName("stop_cond_label")
        self.horizontalLayout_11.addWidget(self.stop_cond_label)
        self.stop_cond = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_cond.sizePolicy().hasHeightForWidth())
        self.stop_cond.setSizePolicy(sizePolicy)
        self.stop_cond.setText("")
        self.stop_cond.setObjectName("stop_cond")
        self.horizontalLayout_11.addWidget(self.stop_cond)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_13)
        self.epochLabel = QtWidgets.QLabel(Dialog)
        self.epochLabel.setObjectName("epochLabel")
        self.horizontalLayout_2.addWidget(self.epochLabel)
        self.epochLine = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epochLine.sizePolicy().hasHeightForWidth())
        self.epochLine.setSizePolicy(sizePolicy)
        self.epochLine.setObjectName("epochLine")
        self.horizontalLayout_2.addWidget(self.epochLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.commentLabel = QtWidgets.QLabel(Dialog)
        self.commentLabel.setObjectName("commentLabel")
        self.horizontalLayout_3.addWidget(self.commentLabel)
        self.commentLine = QtWidgets.QLineEdit(Dialog)
        self.commentLine.setObjectName("commentLine")
        self.horizontalLayout_3.addWidget(self.commentLine)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.svstep_label = QtWidgets.QLabel(Dialog)
        self.svstep_label.setObjectName("svstep_label")
        self.horizontalLayout_15.addWidget(self.svstep_label)
        self.svstepLine = QtWidgets.QLineEdit(Dialog)
        self.svstepLine.setText("")
        self.svstepLine.setObjectName("svstepLine")
        self.horizontalLayout_15.addWidget(self.svstepLine)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tbstep_label = QtWidgets.QLabel(Dialog)
        self.tbstep_label.setObjectName("tbstep_label")
        self.horizontalLayout_14.addWidget(self.tbstep_label)
        self.tbstepLine = QtWidgets.QLineEdit(Dialog)
        self.tbstepLine.setText("")
        self.tbstepLine.setObjectName("tbstepLine")
        self.horizontalLayout_14.addWidget(self.tbstepLine)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.ckptLabel.setText(QtWidgets.QApplication.translate("Dialog", "Checkpoint", None, -1))
        self.ckptLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "choose the .meta file", None, -1))
        self.ckptButton.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.trnPathLabel.setText(QtWidgets.QApplication.translate("Dialog", "trn. repo. path", None, -1))
        self.trnPathLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. \"./train/\"", None, -1))
        self.trnPathButton.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.valPathLabel.setText(QtWidgets.QApplication.translate("Dialog", "val. repo. path", None, -1))
        self.valPathLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. \"./valid/\"", None, -1))
        self.valPathButton.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.tstPathLabel.setText(QtWidgets.QApplication.translate("Dialog", "tst. repo. path", None, -1))
        self.tstPathLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. \"./test/\"", None, -1))
        self.tstPathButton.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.whereToSave_label.setText(QtWidgets.QApplication.translate("Dialog", "where to save models", None, -1))
        self.whereToSave.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "indicate the folder", None, -1))
        self.whereToSaveButton.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.new_init_lr_label.setText(QtWidgets.QApplication.translate("Dialog", "new init. lr.", None, -1))
        self.new_init_lr.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. 1e-3, 1e-4...", None, -1))
        self.new_lr_dec_ratio_label.setText(QtWidgets.QApplication.translate("Dialog", "new lr. dec. ratio", None, -1))
        self.new_lr_dec_ratio.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. 0.1, 0.3, 0.7...", None, -1))
        self.new_lr_dec_period_label.setText(QtWidgets.QApplication.translate("Dialog", "new lr. dec. period", None, -1))
        self.new_lr_dec_period.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. 10, 50, 100...", None, -1))
        self.sampling_gap_label.setText(QtWidgets.QApplication.translate("Dialog", "sampling gap", None, -1))
        self.sampling_gap.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. 5, 50, 100...", None, -1))
        self.stop_cond_label.setText(QtWidgets.QApplication.translate("Dialog", "stop criterea", None, -1))
        self.stop_cond.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. 0.001, 0.0005", None, -1))
        self.epochLabel.setText(QtWidgets.QApplication.translate("Dialog", "Extra epoch", None, -1))
        self.epochLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. 3", None, -1))
        self.commentLabel.setText(QtWidgets.QApplication.translate("Dialog", "Comment", None, -1))
        self.commentLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "e.g. None", None, -1))
        self.svstep_label.setText(QtWidgets.QApplication.translate("Dialog", "save mdl. every", None, -1))
        self.svstepLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "step", None, -1))
        self.tbstep_label.setText(QtWidgets.QApplication.translate("Dialog", "save tb. every", None, -1))
        self.tbstepLine.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "step", None, -1))

