# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/segmentpy/_taskManager/blanketColorPalette.ui',
# licensing of 'src/segmentpy/_taskManager/blanketColorPalette.ui' applies.
#
# Created: Tue May  4 10:18:09 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Blanket(object):
    def setupUi(self, Blanket):
        Blanket.setObjectName("Blanket")
        Blanket.resize(632, 200)
        self.gridLayout = QtWidgets.QGridLayout(Blanket)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_global = QtWidgets.QVBoxLayout()
        self.verticalLayout_global.setObjectName("verticalLayout_global")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.verticalLayout231 = QtWidgets.QVBoxLayout()
        self.verticalLayout231.setObjectName("verticalLayout231")
        self.mdlL = QtWidgets.QLabel(Blanket)
        self.mdlL.setAlignment(QtCore.Qt.AlignCenter)
        self.mdlL.setObjectName("mdlL")
        self.verticalLayout231.addWidget(self.mdlL)
        self.horizontalLayout231 = QtWidgets.QHBoxLayout()
        self.horizontalLayout231.setObjectName("horizontalLayout231")
        self.label2310 = QtWidgets.QLabel(Blanket)
        self.label2310.setObjectName("label2310")
        self.horizontalLayout231.addWidget(self.label2310)
        self.pushButton2310 = QtWidgets.QPushButton(Blanket)
        self.pushButton2310.setObjectName("pushButton2310")
        self.horizontalLayout231.addWidget(self.pushButton2310)
        self.verticalLayout231.addLayout(self.horizontalLayout231)
        self.horizontalLayout_1.addLayout(self.verticalLayout231)
        self.line = QtWidgets.QFrame(Blanket)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_1.addWidget(self.line)
        self.verticalLayout232 = QtWidgets.QVBoxLayout()
        self.verticalLayout232.setObjectName("verticalLayout232")
        self.batchL = QtWidgets.QLabel(Blanket)
        self.batchL.setAlignment(QtCore.Qt.AlignCenter)
        self.batchL.setObjectName("batchL")
        self.verticalLayout232.addWidget(self.batchL)
        self.horizontalLayout232 = QtWidgets.QHBoxLayout()
        self.horizontalLayout232.setObjectName("horizontalLayout232")
        self.label2320 = QtWidgets.QLabel(Blanket)
        self.label2320.setObjectName("label2320")
        self.horizontalLayout232.addWidget(self.label2320)
        self.pushButton2320 = QtWidgets.QPushButton(Blanket)
        self.pushButton2320.setObjectName("pushButton2320")
        self.horizontalLayout232.addWidget(self.pushButton2320)
        self.verticalLayout232.addLayout(self.horizontalLayout232)
        self.horizontalLayout_1.addLayout(self.verticalLayout232)
        self.line_2 = QtWidgets.QFrame(Blanket)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_1.addWidget(self.line_2)
        self.verticalLayout233 = QtWidgets.QVBoxLayout()
        self.verticalLayout233.setObjectName("verticalLayout233")
        self.kernelL = QtWidgets.QLabel(Blanket)
        self.kernelL.setAlignment(QtCore.Qt.AlignCenter)
        self.kernelL.setObjectName("kernelL")
        self.verticalLayout233.addWidget(self.kernelL)
        self.horizontalLayout233 = QtWidgets.QHBoxLayout()
        self.horizontalLayout233.setObjectName("horizontalLayout233")
        self.label2330 = QtWidgets.QLabel(Blanket)
        self.label2330.setObjectName("label2330")
        self.horizontalLayout233.addWidget(self.label2330)
        self.pushButton2330 = QtWidgets.QPushButton(Blanket)
        self.pushButton2330.setObjectName("pushButton2330")
        self.horizontalLayout233.addWidget(self.pushButton2330)
        self.verticalLayout233.addLayout(self.horizontalLayout233)
        self.horizontalLayout_1.addLayout(self.verticalLayout233)
        self.verticalLayout_global.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout234 = QtWidgets.QVBoxLayout()
        self.verticalLayout234.setObjectName("verticalLayout234")
        self.ncL = QtWidgets.QLabel(Blanket)
        self.ncL.setAlignment(QtCore.Qt.AlignCenter)
        self.ncL.setObjectName("ncL")
        self.verticalLayout234.addWidget(self.ncL)
        self.horizontalLayout234 = QtWidgets.QHBoxLayout()
        self.horizontalLayout234.setObjectName("horizontalLayout234")
        self.label2340 = QtWidgets.QLabel(Blanket)
        self.label2340.setObjectName("label2340")
        self.horizontalLayout234.addWidget(self.label2340)
        self.pushButton2340 = QtWidgets.QPushButton(Blanket)
        self.pushButton2340.setObjectName("pushButton2340")
        self.horizontalLayout234.addWidget(self.pushButton2340)
        self.verticalLayout234.addLayout(self.horizontalLayout234)
        self.horizontalLayout_7.addLayout(self.verticalLayout234)
        self.line_3 = QtWidgets.QFrame(Blanket)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.verticalLayout235 = QtWidgets.QVBoxLayout()
        self.verticalLayout235.setObjectName("verticalLayout235")
        self.lrL = QtWidgets.QLabel(Blanket)
        self.lrL.setAlignment(QtCore.Qt.AlignCenter)
        self.lrL.setObjectName("lrL")
        self.verticalLayout235.addWidget(self.lrL)
        self.horizontalLayout235 = QtWidgets.QHBoxLayout()
        self.horizontalLayout235.setObjectName("horizontalLayout235")
        self.label2350 = QtWidgets.QLabel(Blanket)
        self.label2350.setObjectName("label2350")
        self.horizontalLayout235.addWidget(self.label2350)
        self.pushButton2350 = QtWidgets.QPushButton(Blanket)
        self.pushButton2350.setObjectName("pushButton2350")
        self.horizontalLayout235.addWidget(self.pushButton2350)
        self.verticalLayout235.addLayout(self.horizontalLayout235)
        self.horizontalLayout_7.addLayout(self.verticalLayout235)
        self.line_4 = QtWidgets.QFrame(Blanket)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_7.addWidget(self.line_4)
        self.verticalLayout236 = QtWidgets.QVBoxLayout()
        self.verticalLayout236.setObjectName("verticalLayout236")
        self.lkL = QtWidgets.QLabel(Blanket)
        self.lkL.setAlignment(QtCore.Qt.AlignCenter)
        self.lkL.setObjectName("lkL")
        self.verticalLayout236.addWidget(self.lkL)
        self.horizontalLayout236 = QtWidgets.QHBoxLayout()
        self.horizontalLayout236.setObjectName("horizontalLayout236")
        self.label2360 = QtWidgets.QLabel(Blanket)
        self.label2360.setObjectName("label2360")
        self.horizontalLayout236.addWidget(self.label2360)
        self.pushButton2360 = QtWidgets.QPushButton(Blanket)
        self.pushButton2360.setObjectName("pushButton2360")
        self.horizontalLayout236.addWidget(self.pushButton2360)
        self.verticalLayout236.addLayout(self.horizontalLayout236)
        self.horizontalLayout_7.addLayout(self.verticalLayout236)
        self.verticalLayout_global.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_global)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Blanket)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Blanket)
        QtCore.QMetaObject.connectSlotsByName(Blanket)

    def retranslateUi(self, Blanket):
        Blanket.setWindowTitle(QtWidgets.QApplication.translate("Blanket", "Form", None, -1))
        self.mdlL.setText(QtWidgets.QApplication.translate("Blanket", "model", None, -1))
        self.label2310.setText(QtWidgets.QApplication.translate("Blanket", "TextLabel", None, -1))
        self.pushButton2310.setText(QtWidgets.QApplication.translate("Blanket", "PushButton", None, -1))
        self.batchL.setText(QtWidgets.QApplication.translate("Blanket", "batch", None, -1))
        self.label2320.setText(QtWidgets.QApplication.translate("Blanket", "TextLabel", None, -1))
        self.pushButton2320.setText(QtWidgets.QApplication.translate("Blanket", "PushButton", None, -1))
        self.kernelL.setText(QtWidgets.QApplication.translate("Blanket", "kernel", None, -1))
        self.label2330.setText(QtWidgets.QApplication.translate("Blanket", "TextLabel", None, -1))
        self.pushButton2330.setText(QtWidgets.QApplication.translate("Blanket", "PushButton", None, -1))
        self.ncL.setText(QtWidgets.QApplication.translate("Blanket", "nb_conv", None, -1))
        self.label2340.setText(QtWidgets.QApplication.translate("Blanket", "TextLabel", None, -1))
        self.pushButton2340.setText(QtWidgets.QApplication.translate("Blanket", "PushButton", None, -1))
        self.lrL.setText(QtWidgets.QApplication.translate("Blanket", "learning rate: init", None, -1))
        self.label2350.setText(QtWidgets.QApplication.translate("Blanket", "TextLabel", None, -1))
        self.pushButton2350.setText(QtWidgets.QApplication.translate("Blanket", "PushButton", None, -1))
        self.lkL.setText(QtWidgets.QApplication.translate("Blanket", "learning rate: decay", None, -1))
        self.label2360.setText(QtWidgets.QApplication.translate("Blanket", "TextLabel", None, -1))
        self.pushButton2360.setText(QtWidgets.QApplication.translate("Blanket", "PushButton", None, -1))

