# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_taskManager/dialog.ui',
# licensing of '_taskManager/dialog.ui' applies.
#
# Created: Fri Apr 23 11:01:14 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(884, 811)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.mdl = QtWidgets.QLineEdit(Dialog)
        self.mdl.setObjectName("mdl")
        self.verticalLayout_2.addWidget(self.mdl)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.ksize = QtWidgets.QLineEdit(Dialog)
        self.ksize.setObjectName("ksize")
        self.verticalLayout_2.addWidget(self.ksize)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.nbconv = QtWidgets.QLineEdit(Dialog)
        self.nbconv.setObjectName("nbconv")
        self.verticalLayout_2.addWidget(self.nbconv)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.winsize = QtWidgets.QLineEdit(Dialog)
        self.winsize.setText("")
        self.winsize.setObjectName("winsize")
        self.verticalLayout_2.addWidget(self.winsize)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.batsize = QtWidgets.QLineEdit(Dialog)
        self.batsize.setObjectName("batsize")
        self.verticalLayout_2.addWidget(self.batsize)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.nbepoch = QtWidgets.QLineEdit(Dialog)
        self.nbepoch.setText("")
        self.nbepoch.setObjectName("nbepoch")
        self.verticalLayout_2.addWidget(self.nbepoch)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.batnorm = QtWidgets.QComboBox(Dialog)
        self.batnorm.setObjectName("batnorm")
        self.batnorm.addItem("")
        self.batnorm.addItem("")
        self.verticalLayout_2.addWidget(self.batnorm)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.aug = QtWidgets.QComboBox(Dialog)
        self.aug.setObjectName("aug")
        self.aug.addItem("")
        self.aug.addItem("")
        self.verticalLayout_2.addWidget(self.aug)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.dropout = QtWidgets.QLineEdit(Dialog)
        self.dropout.setObjectName("dropout")
        self.verticalLayout_2.addWidget(self.dropout)
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.sampling_gap = QtWidgets.QLineEdit(Dialog)
        self.sampling_gap.setObjectName("sampling_gap")
        self.verticalLayout_2.addWidget(self.sampling_gap)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.correction = QtWidgets.QLineEdit(Dialog)
        self.correction.setObjectName("correction")
        self.verticalLayout_2.addWidget(self.correction)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.lrtype = QtWidgets.QComboBox(Dialog)
        self.lrtype.setObjectName("lrtype")
        self.lrtype.addItem("")
        self.lrtype.addItem("")
        self.lrtype.addItem("")
        self.verticalLayout.addWidget(self.lrtype)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.initlr = QtWidgets.QLineEdit(Dialog)
        self.initlr.setObjectName("initlr")
        self.verticalLayout.addWidget(self.initlr)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.kparam = QtWidgets.QLineEdit(Dialog)
        self.kparam.setObjectName("kparam")
        self.verticalLayout.addWidget(self.kparam)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.pparam = QtWidgets.QLineEdit(Dialog)
        self.pparam.setObjectName("pparam")
        self.verticalLayout.addWidget(self.pparam)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.actfn = QtWidgets.QComboBox(Dialog)
        self.actfn.setObjectName("actfn")
        self.actfn.addItem("")
        self.actfn.addItem("")
        self.actfn.addItem("")
        self.actfn.addItem("")
        self.actfn.addItem("")
        self.verticalLayout.addWidget(self.actfn)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.lossfn = QtWidgets.QComboBox(Dialog)
        self.lossfn.setObjectName("lossfn")
        self.lossfn.addItem("")
        self.lossfn.addItem("")
        self.lossfn.addItem("")
        self.verticalLayout.addWidget(self.lossfn)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.clsReg = QtWidgets.QComboBox(Dialog)
        self.clsReg.setObjectName("clsReg")
        self.clsReg.addItem("")
        self.clsReg.addItem("")
        self.verticalLayout.addWidget(self.clsReg)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.svsteps = QtWidgets.QLineEdit(Dialog)
        self.svsteps.setObjectName("svsteps")
        self.verticalLayout.addWidget(self.svsteps)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.tbstep = QtWidgets.QLineEdit(Dialog)
        self.tbstep.setObjectName("tbstep")
        self.verticalLayout.addWidget(self.tbstep)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.criterion = QtWidgets.QLineEdit(Dialog)
        self.criterion.setObjectName("criterion")
        self.verticalLayout.addWidget(self.criterion)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.comment = QtWidgets.QLineEdit(Dialog)
        self.comment.setObjectName("comment")
        self.verticalLayout_3.addWidget(self.comment)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.log_dir_line = QtWidgets.QLineEdit(Dialog)
        self.log_dir_line.setObjectName("log_dir_line")
        self.horizontalLayout_5.addWidget(self.log_dir_line)
        self.log_dir_button = QtWidgets.QPushButton(Dialog)
        self.log_dir_button.setObjectName("log_dir_button")
        self.horizontalLayout_5.addWidget(self.log_dir_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.trn_dir_line = QtWidgets.QLineEdit(Dialog)
        self.trn_dir_line.setObjectName("trn_dir_line")
        self.horizontalLayout_3.addWidget(self.trn_dir_line)
        self.trn_dir_button = QtWidgets.QPushButton(Dialog)
        self.trn_dir_button.setObjectName("trn_dir_button")
        self.horizontalLayout_3.addWidget(self.trn_dir_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.val_dir_line = QtWidgets.QLineEdit(Dialog)
        self.val_dir_line.setObjectName("val_dir_line")
        self.horizontalLayout_2.addWidget(self.val_dir_line)
        self.val_dir_button = QtWidgets.QPushButton(Dialog)
        self.val_dir_button.setObjectName("val_dir_button")
        self.horizontalLayout_2.addWidget(self.val_dir_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.test_dir_line = QtWidgets.QLineEdit(Dialog)
        self.test_dir_line.setObjectName("test_dir_line")
        self.horizontalLayout_4.addWidget(self.test_dir_line)
        self.test_dir_button = QtWidgets.QPushButton(Dialog)
        self.test_dir_button.setObjectName("test_dir_button")
        self.horizontalLayout_4.addWidget(self.test_dir_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "model name", None, -1))
        self.mdl.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. LRCS, Unet, custom...)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "kernel size", None, -1))
        self.ksize.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 3, 5, 7...)", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "number of convolution minimum per layer", None, -1))
        self.nbconv.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 16, 32,...) depand on memory", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "window size", None, -1))
        self.winsize.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(80, 512...) multiple of 8 if 3x MaxPool", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "batch size", None, -1))
        self.batsize.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 8, 16...) depend on memory", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "number of epoch", None, -1))
        self.nbepoch.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 5, 10...) integer", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "batch normalization", None, -1))
        self.batnorm.setItemText(0, QtWidgets.QApplication.translate("Dialog", "True", None, -1))
        self.batnorm.setItemText(1, QtWidgets.QApplication.translate("Dialog", "False", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "data augmentation", None, -1))
        self.aug.setItemText(0, QtWidgets.QApplication.translate("Dialog", "True", None, -1))
        self.aug.setItemText(1, QtWidgets.QApplication.translate("Dialog", "False", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "dropout probability", None, -1))
        self.dropout.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 0.1, 0.5, 1.0...) float", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Dialog", "sampling gap", None, -1))
        self.sampling_gap.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 5, 100, 200...) integer", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("Dialog", "input image correction (beamline dependant)", None, -1))
        self.correction.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 1e3 if input image ranges at 1e-3; 0.0039 for 0-255) float", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "learning rate decay type", None, -1))
        self.lrtype.setItemText(0, QtWidgets.QApplication.translate("Dialog", "ramp", None, -1))
        self.lrtype.setItemText(1, QtWidgets.QApplication.translate("Dialog", "exp", None, -1))
        self.lrtype.setItemText(2, QtWidgets.QApplication.translate("Dialog", "constant", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "initial learning rate", None, -1))
        self.initlr.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 1e-4, 0.01,...) float", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog", "k parameter in decay type", None, -1))
        self.kparam.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 0.3, 0.1, 0.5) float", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog", "decay periode / decay every n epoch", None, -1))
        self.pparam.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 1, 0.5, 4) float ", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog", "activation function type", None, -1))
        self.actfn.setItemText(0, QtWidgets.QApplication.translate("Dialog", "leaky", None, -1))
        self.actfn.setItemText(1, QtWidgets.QApplication.translate("Dialog", "relu", None, -1))
        self.actfn.setItemText(2, QtWidgets.QApplication.translate("Dialog", "sigmoid", None, -1))
        self.actfn.setItemText(3, QtWidgets.QApplication.translate("Dialog", "tanh", None, -1))
        self.actfn.setItemText(4, QtWidgets.QApplication.translate("Dialog", "custom", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Dialog", "loss function type", None, -1))
        self.lossfn.setItemText(0, QtWidgets.QApplication.translate("Dialog", "DSC", None, -1))
        self.lossfn.setItemText(1, QtWidgets.QApplication.translate("Dialog", "cross_entropy", None, -1))
        self.lossfn.setItemText(2, QtWidgets.QApplication.translate("Dialog", "MSE", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Dialog", "classification / regression", None, -1))
        self.clsReg.setItemText(0, QtWidgets.QApplication.translate("Dialog", "classification", None, -1))
        self.clsReg.setItemText(1, QtWidgets.QApplication.translate("Dialog", "regression", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog", "save model every n steps", None, -1))
        self.svsteps.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 500...) integer", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Dialog", "tb: gradients and weights every n steps", None, -1))
        self.tbstep.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 50...) integer", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Dialog", "stopping criterion", None, -1))
        self.criterion.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "(e.g. 0.002) float", None, -1))
        self.comment.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "enter extra comment here", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Dialog", "save model to:", None, -1))
        self.log_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "default: <SegmentPy installation folder>/logs/", None, -1))
        self.log_dir_button.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Dialog", "Trn. ds. repo.:", None, -1))
        self.trn_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "default: <SegmentPy installation folder>/train/", None, -1))
        self.trn_dir_button.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Dialog", "Val. ds. repo.:", None, -1))
        self.val_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "default: <SegmentPy installation folder>/valid/", None, -1))
        self.val_dir_button.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Dialog", "Tst. ds. repo.:", None, -1))
        self.test_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "default: <SegmentPy installation folder>/test/", None, -1))
        self.test_dir_button.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))

