# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/segmentpy/_taskManager/gridSearch_dialog.ui',
# licensing of 'src/segmentpy/_taskManager/gridSearch_dialog.ui' applies.
#
# Created: Sun May  2 18:22:27 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_gridSearch_dialog(object):
    def setupUi(self, gridSearch_dialog):
        gridSearch_dialog.setObjectName("gridSearch_dialog")
        gridSearch_dialog.resize(714, 598)
        self.gridLayout = QtWidgets.QGridLayout(gridSearch_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.model_line = QtWidgets.QLineEdit(gridSearch_dialog)
        self.model_line.setObjectName("model_line")
        self.horizontalLayout_10.addWidget(self.model_line)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(gridSearch_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.kernel_size = QtWidgets.QLineEdit(gridSearch_dialog)
        self.kernel_size.setObjectName("kernel_size")
        self.horizontalLayout.addWidget(self.kernel_size)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.nb_conv = QtWidgets.QLineEdit(gridSearch_dialog)
        self.nb_conv.setObjectName("nb_conv")
        self.horizontalLayout_2.addWidget(self.nb_conv)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.batch_size = QtWidgets.QLineEdit(gridSearch_dialog)
        self.batch_size.setObjectName("batch_size")
        self.horizontalLayout_4.addWidget(self.batch_size)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.init_lr = QtWidgets.QLineEdit(gridSearch_dialog)
        self.init_lr.setObjectName("init_lr")
        self.horizontalLayout_3.addWidget(self.init_lr)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.decay_ratio = QtWidgets.QLineEdit(gridSearch_dialog)
        self.decay_ratio.setObjectName("decay_ratio")
        self.horizontalLayout_5.addWidget(self.decay_ratio)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.correctionLine = QtWidgets.QLineEdit(gridSearch_dialog)
        self.correctionLine.setObjectName("correctionLine")
        self.horizontalLayout_11.addWidget(self.correctionLine)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.sample_gapLine = QtWidgets.QLineEdit(gridSearch_dialog)
        self.sample_gapLine.setObjectName("sample_gapLine")
        self.horizontalLayout_12.addWidget(self.sample_gapLine)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.stop_criterionLine = QtWidgets.QLineEdit(gridSearch_dialog)
        self.stop_criterionLine.setObjectName("stop_criterionLine")
        self.horizontalLayout_13.addWidget(self.stop_criterionLine)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(gridSearch_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.comment = QtWidgets.QLineEdit(gridSearch_dialog)
        self.comment.setObjectName("comment")
        self.verticalLayout_2.addWidget(self.comment)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.trn_dir_line = QtWidgets.QLineEdit(gridSearch_dialog)
        self.trn_dir_line.setObjectName("trn_dir_line")
        self.horizontalLayout_7.addWidget(self.trn_dir_line)
        self.trn_dir_button = QtWidgets.QPushButton(gridSearch_dialog)
        self.trn_dir_button.setObjectName("trn_dir_button")
        self.horizontalLayout_7.addWidget(self.trn_dir_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.val_dir_line = QtWidgets.QLineEdit(gridSearch_dialog)
        self.val_dir_line.setObjectName("val_dir_line")
        self.horizontalLayout_9.addWidget(self.val_dir_line)
        self.val_dir_button = QtWidgets.QPushButton(gridSearch_dialog)
        self.val_dir_button.setObjectName("val_dir_button")
        self.horizontalLayout_9.addWidget(self.val_dir_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_21 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.test_dir_line = QtWidgets.QLineEdit(gridSearch_dialog)
        self.test_dir_line.setObjectName("test_dir_line")
        self.horizontalLayout_6.addWidget(self.test_dir_line)
        self.test_dir_button = QtWidgets.QPushButton(gridSearch_dialog)
        self.test_dir_button.setObjectName("test_dir_button")
        self.horizontalLayout_6.addWidget(self.test_dir_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(gridSearch_dialog)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.log_dir_line = QtWidgets.QLineEdit(gridSearch_dialog)
        self.log_dir_line.setObjectName("log_dir_line")
        self.horizontalLayout_8.addWidget(self.log_dir_line)
        self.log_dir_button = QtWidgets.QPushButton(gridSearch_dialog)
        self.log_dir_button.setObjectName("log_dir_button")
        self.horizontalLayout_8.addWidget(self.log_dir_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.line_2 = QtWidgets.QFrame(gridSearch_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(gridSearch_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(gridSearch_dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), gridSearch_dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), gridSearch_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(gridSearch_dialog)

    def retranslateUi(self, gridSearch_dialog):
        gridSearch_dialog.setWindowTitle(QtWidgets.QApplication.translate("gridSearch_dialog", "Dialog", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "model", None, -1))
        self.model_line.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "LRCSNet, UNet, SegNet", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "kernel size", None, -1))
        self.kernel_size.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "suggestion: 3, 5 (seperated by , or ; or /)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "basic nb. conv.", None, -1))
        self.nb_conv.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g. 32, 48, 64... (integer; seperated by , or ; or /)", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "batch size", None, -1))
        self.batch_size.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g. 2, 4, 6... (interger; depanding on your device\'s memory; seperated by , or ; or /)", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "initial learning rate", None, -1))
        self.init_lr.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g. 1e-3, 1e-5... (depanding on your device\'s memory; seperated by , or ; or /)", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "learning rate decay ratio", None, -1))
        self.decay_ratio.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g. 0.1, 0.5... (between 0-1; seperated by , or ; or /)", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "correction", None, -1))
        self.correctionLine.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g., 1e-2 for input image ranging 0-100", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "sample gap", None, -1))
        self.sample_gapLine.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g., gap of sampling 5, 50, 100 depending on the dataset size", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "stop. crit.", None, -1))
        self.stop_criterionLine.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "e.g., 0.01, 1e-3", None, -1))
        self.comment.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "enter extra comment here", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "Trn. ds. repo.:", None, -1))
        self.trn_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "default: <SegmentPy installation folder>/train/", None, -1))
        self.trn_dir_button.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "...", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "Val. ds. repo.:", None, -1))
        self.val_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "default: <SegmentPy installation folder>/valid/", None, -1))
        self.val_dir_button.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "...", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "Tst. ds. repo.:", None, -1))
        self.test_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "default: <SegmentPy installation folder>/test/", None, -1))
        self.test_dir_button.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "...", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "save model to:", None, -1))
        self.log_dir_line.setPlaceholderText(QtWidgets.QApplication.translate("gridSearch_dialog", "default: <SegmentPy installation folder>/logs/", None, -1))
        self.log_dir_button.setText(QtWidgets.QApplication.translate("gridSearch_dialog", "...", None, -1))

