# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/segmentpy/_taskManager/mainwindow.ui',
# licensing of 'src/segmentpy/_taskManager/mainwindow.ui' applies.
#
# Created: Mon May  3 17:12:47 2021
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_LRCSNet(object):
    def setupUi(self, LRCSNet):
        LRCSNet.setObjectName("LRCSNet")
        LRCSNet.resize(1178, 718)
        self.centralwidget = QtWidgets.QWidget(LRCSNet)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(0, 36))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_button.setIcon(icon)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_2.addWidget(self.start_button)
        self.loop_button = QtWidgets.QPushButton(self.centralwidget)
        self.loop_button.setMinimumSize(QtCore.QSize(0, 36))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/exchange_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../img/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.loop_button.setIcon(icon1)
        self.loop_button.setCheckable(True)
        self.loop_button.setObjectName("loop_button")
        self.horizontalLayout_2.addWidget(self.loop_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 36))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stop_button.setIcon(icon2)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setMinimumSize(QtCore.QSize(0, 36))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../img/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add_button.setIcon(icon3)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.add_button)
        self.clean_button = QtWidgets.QPushButton(self.centralwidget)
        self.clean_button.setMinimumSize(QtCore.QSize(0, 36))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../img/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.clean_button.setIcon(icon4)
        self.clean_button.setObjectName("clean_button")
        self.horizontalLayout_2.addWidget(self.clean_button)
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setMinimumSize(QtCore.QSize(0, 36))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("../img/reply.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.forward_button.setIcon(icon5)
        self.forward_button.setObjectName("forward_button")
        self.horizontalLayout_2.addWidget(self.forward_button)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 36))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("../img/resume.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon6)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setMinimumSize(QtCore.QSize(0, 36))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("rubik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap("../img/rubik.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.predict_button.setIcon(icon7)
        self.predict_button.setIconSize(QtCore.QSize(20, 20))
        self.predict_button.setObjectName("predict_button")
        self.horizontalLayout_2.addWidget(self.predict_button)
        self.dashboard_button = QtWidgets.QPushButton(self.centralwidget)
        self.dashboard_button.setMinimumSize(QtCore.QSize(0, 36))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("speedometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap("../img/speedometer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashboard_button.setIcon(icon8)
        self.dashboard_button.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button.setObjectName("dashboard_button")
        self.horizontalLayout_2.addWidget(self.dashboard_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(801, 601))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setRowCount(28)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(28)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.tableWidget.setItem(5, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(128, 255, 7))
        brush.setStyle(QtCore.Qt.NoBrush)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(181, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.AvailableGPUs = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AvailableGPUs.sizePolicy().hasHeightForWidth())
        self.AvailableGPUs.setSizePolicy(sizePolicy)
        self.AvailableGPUs.setMaximumSize(QtCore.QSize(181, 16777215))
        self.AvailableGPUs.setObjectName("AvailableGPUs")
        self.verticalLayout.addWidget(self.AvailableGPUs)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(181, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ongoing_process = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ongoing_process.sizePolicy().hasHeightForWidth())
        self.ongoing_process.setSizePolicy(sizePolicy)
        self.ongoing_process.setMaximumSize(QtCore.QSize(181, 16777215))
        self.ongoing_process.setObjectName("ongoing_process")
        self.verticalLayout.addWidget(self.ongoing_process)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        LRCSNet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setEnabled(True)
        self.menuMenu.setObjectName("menuMenu")
        self.menuPlugin = QtWidgets.QMenu(self.menubar)
        self.menuPlugin.setObjectName("menuPlugin")
        self.menuVisualization = QtWidgets.QMenu(self.menubar)
        self.menuVisualization.setObjectName("menuVisualization")
        self.menuHands_off = QtWidgets.QMenu(self.menubar)
        self.menuHands_off.setObjectName("menuHands_off")
        LRCSNet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LRCSNet)
        self.statusbar.setObjectName("statusbar")
        LRCSNet.setStatusBar(self.statusbar)
        self.About_us = QtWidgets.QAction(LRCSNet)
        self.About_us.setObjectName("About_us")
        self.Activations = QtWidgets.QAction(LRCSNet)
        self.Activations.setObjectName("Activations")
        self.Exit = QtWidgets.QAction(LRCSNet)
        self.Exit.setObjectName("Exit")
        self.Loss_Landscape = QtWidgets.QAction(LRCSNet)
        self.Loss_Landscape.setObjectName("Loss_Landscape")
        self.Random_Forest = QtWidgets.QAction(LRCSNet)
        self.Random_Forest.setObjectName("Random_Forest")
        self.Metrics = QtWidgets.QAction(LRCSNet)
        self.Metrics.setObjectName("Metrics")
        self.Preferences = QtWidgets.QAction(LRCSNet)
        self.Preferences.setObjectName("Preferences")
        self.ActViewer = QtWidgets.QAction(LRCSNet)
        self.ActViewer.setObjectName("ActViewer")
        self.Volumes_Viewer = QtWidgets.QAction(LRCSNet)
        self.Volumes_Viewer.setObjectName("Volumes_Viewer")
        self.AugViewer = QtWidgets.QAction(LRCSNet)
        self.AugViewer.setObjectName("AugViewer")
        self.GradViewer = QtWidgets.QAction(LRCSNet)
        self.GradViewer.setObjectName("GradViewer")
        self.Thresholding = QtWidgets.QAction(LRCSNet)
        self.Thresholding.setObjectName("Thresholding")
        self.actionGrid_Search = QtWidgets.QAction(LRCSNet)
        self.actionGrid_Search.setObjectName("actionGrid_Search")
        self.actionGassian_Process = QtWidgets.QAction(LRCSNet)
        self.actionGassian_Process.setObjectName("actionGassian_Process")
        self.actionExtract_Result = QtWidgets.QAction(LRCSNet)
        self.actionExtract_Result.setObjectName("actionExtract_Result")
        self.menuMenu.addAction(self.About_us)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.Preferences)
        self.menuMenu.addAction(self.Exit)
        self.menuPlugin.addAction(self.Activations)
        self.menuPlugin.addAction(self.Loss_Landscape)
        self.menuPlugin.addAction(self.Random_Forest)
        self.menuPlugin.addAction(self.Metrics)
        self.menuPlugin.addAction(self.Thresholding)
        self.menuPlugin.addAction(self.actionExtract_Result)
        self.menuVisualization.addAction(self.ActViewer)
        self.menuVisualization.addAction(self.Volumes_Viewer)
        self.menuVisualization.addAction(self.AugViewer)
        self.menuVisualization.addAction(self.GradViewer)
        self.menuHands_off.addAction(self.actionGrid_Search)
        self.menuHands_off.addAction(self.actionGassian_Process)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuVisualization.menuAction())
        self.menubar.addAction(self.menuPlugin.menuAction())
        self.menubar.addAction(self.menuHands_off.menuAction())

        self.retranslateUi(LRCSNet)
        QtCore.QMetaObject.connectSlotsByName(LRCSNet)

    def retranslateUi(self, LRCSNet):
        LRCSNet.setWindowTitle(QtWidgets.QApplication.translate("LRCSNet", "MainWindow", None, -1))
        self.start_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Start(A)", None, -1))
        self.start_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "A", None, -1))
        self.loop_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Loop(S)", None, -1))
        self.loop_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "S", None, -1))
        self.stop_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Stop(D)", None, -1))
        self.stop_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "D", None, -1))
        self.add_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Add(Q)", None, -1))
        self.add_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "Q", None, -1))
        self.clean_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Clean(W)", None, -1))
        self.clean_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "W", None, -1))
        self.forward_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Forward(E)", None, -1))
        self.forward_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "E", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("LRCSNet", "Resume(Z)", None, -1))
        self.pushButton.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "Z", None, -1))
        self.predict_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Predict(X)", None, -1))
        self.predict_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "X", None, -1))
        self.dashboard_button.setText(QtWidgets.QApplication.translate("LRCSNet", "Dashboard(C)", None, -1))
        self.dashboard_button.setShortcut(QtWidgets.QApplication.translate("LRCSNet", "C", None, -1))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "model", None, -1))
        self.tableWidget.item(1, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "conv nb", None, -1))
        self.tableWidget.item(2, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "kernel size", None, -1))
        self.tableWidget.item(3, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "batch size", None, -1))
        self.tableWidget.item(4, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "window size", None, -1))
        self.tableWidget.item(5, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "nb_epoch", None, -1))
        self.tableWidget.item(6, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "lr type", None, -1))
        self.tableWidget.item(7, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "init lr", None, -1))
        self.tableWidget.item(8, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "k param", None, -1))
        self.tableWidget.item(9, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "p param", None, -1))
        self.tableWidget.item(10, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "loss fn", None, -1))
        self.tableWidget.item(11, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "act fn", None, -1))
        self.tableWidget.item(12, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "batch norm", None, -1))
        self.tableWidget.item(13, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "augmentation", None, -1))
        self.tableWidget.item(14, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "dropout", None, -1))
        self.tableWidget.item(15, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "sv step", None, -1))
        self.tableWidget.item(16, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "tb step", None, -1))
        self.tableWidget.item(17, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "mode", None, -1))
        self.tableWidget.item(18, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "comment", None, -1))
        self.tableWidget.item(19, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "sampl. gap", None, -1))
        self.tableWidget.item(20, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "stop. crit.", None, -1))
        self.tableWidget.item(21, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "correction", None, -1))
        self.tableWidget.item(22, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "trn repo path", None, -1))
        self.tableWidget.item(23, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "val repo path", None, -1))
        self.tableWidget.item(24, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "tst repo path", None, -1))
        self.tableWidget.item(25, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "mdl. saved path", None, -1))
        self.tableWidget.item(26, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "ckpt path", None, -1))
        self.tableWidget.item(27, 0).setText(QtWidgets.QApplication.translate("LRCSNet", "nodes", None, -1))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtWidgets.QApplication.translate("LRCSNet", "Available GPUs:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("LRCSNet", "Ongoing Process:", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("LRCSNet", "Menu", None, -1))
        self.menuPlugin.setTitle(QtWidgets.QApplication.translate("LRCSNet", "Plug-ins", None, -1))
        self.menuVisualization.setTitle(QtWidgets.QApplication.translate("LRCSNet", "Visualization", None, -1))
        self.menuHands_off.setTitle(QtWidgets.QApplication.translate("LRCSNet", "Hands-off", None, -1))
        self.About_us.setText(QtWidgets.QApplication.translate("LRCSNet", "About us", None, -1))
        self.Activations.setText(QtWidgets.QApplication.translate("LRCSNet", "Activations", None, -1))
        self.Exit.setText(QtWidgets.QApplication.translate("LRCSNet", "Exit", None, -1))
        self.Loss_Landscape.setText(QtWidgets.QApplication.translate("LRCSNet", "Loss-Landscape", None, -1))
        self.Random_Forest.setText(QtWidgets.QApplication.translate("LRCSNet", "Random-Forest", None, -1))
        self.Metrics.setText(QtWidgets.QApplication.translate("LRCSNet", "Metrics", None, -1))
        self.Preferences.setText(QtWidgets.QApplication.translate("LRCSNet", "Preferences", None, -1))
        self.ActViewer.setText(QtWidgets.QApplication.translate("LRCSNet", "ActViewer", None, -1))
        self.Volumes_Viewer.setText(QtWidgets.QApplication.translate("LRCSNet", "VolViewer", None, -1))
        self.AugViewer.setText(QtWidgets.QApplication.translate("LRCSNet", "AugViewer", None, -1))
        self.GradViewer.setText(QtWidgets.QApplication.translate("LRCSNet", "GradViewer", None, -1))
        self.Thresholding.setText(QtWidgets.QApplication.translate("LRCSNet", "Threshold", None, -1))
        self.actionGrid_Search.setText(QtWidgets.QApplication.translate("LRCSNet", "Grid Search", None, -1))
        self.actionGassian_Process.setText(QtWidgets.QApplication.translate("LRCSNet", "Gassian Process", None, -1))
        self.actionExtract_Result.setText(QtWidgets.QApplication.translate("LRCSNet", "Extract Result", None, -1))

